config/routes.rb
Rails.application.routes.draw do
  resources :visitas_agendadas
  resources :cadastro_cachorros
  resources :contato
  resources :pagina_inicial
  devise_for :users
  get 'pagina_inicial/index'
  get 'contato/index'
  get 'login/index'
  get 'criar_conta/index'
  get 'cadastro_usuarios/index'

  root 'pagina_inicial#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cadastro_cachorro.rb
class CadastroCachorro < ApplicationRecord
    has_one_attached :foto
end

app/models/user.rb
class User < ApplicationRecord
  has_many :visitas_agendadas
  enum status: [ :active, :archived ]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visitas_agendada.rb
class VisitasAgendada < ApplicationRecord
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

    before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  private
  def user_not_authorized
      flash[:alert] = "Sem permissao"
      redirect_to(request.referrer || root_path)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] },:name, :telefone, :email, :password) }
  end
end

app/controllers/cadastro_cachorros_controller.rb
class CadastroCachorrosController < ApplicationController
  before_action :set_cadastro_cachorro, only: [:show, :edit, :update, :destroy]

  # GET /cadastro_cachorros
  # GET /cadastro_cachorros.json
  def index
    @cadastro_cachorros = CadastroCachorro.all
  end

  # GET /cadastro_cachorros/1
  # GET /cadastro_cachorros/1.json
  def show
  end

  # GET /cadastro_cachorros/new
  def new
    @cadastro_cachorro = CadastroCachorro.new
  end

  # GET /cadastro_cachorros/1/edit
  def edit
  end

  # POST /cadastro_cachorros
  # POST /cadastro_cachorros.json
  def create
    @cadastro_cachorro = CadastroCachorro.new(cadastro_cachorro_params)

    respond_to do |format|
      if @cadastro_cachorro.save
        format.html { redirect_to cadastro_cachorros_path, notice: 'Cadastro cachorro was successfully created.' }
        format.json { render :show, status: :created, location: @cadastro_cachorro }
      else
        format.html { render :new }
        format.json { render json: @cadastro_cachorro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastro_cachorros/1
  # PATCH/PUT /cadastro_cachorros/1.json
  def update
    respond_to do |format|
      if @cadastro_cachorro.update(cadastro_cachorro_params)
        format.html { redirect_to @cadastro_cachorro, notice: 'Cadastro cachorro was successfully updated.' }
        format.json { render :show, status: :ok, location: @cadastro_cachorro }
      else
        format.html { render :edit }
        format.json { render json: @cadastro_cachorro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastro_cachorros/1
  # DELETE /cadastro_cachorros/1.json
  def destroy
    @cadastro_cachorro.destroy
    respond_to do |format|
      format.html { redirect_to cadastro_cachorros_url, notice: 'Cadastro cachorro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro_cachorro
      @cadastro_cachorro = CadastroCachorro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadastro_cachorro_params
      params.require(:cadastro_cachorro).permit(:nome, :raca, :sexo, :idade, :foto)
    end
end

app/controllers/cadastro_usuarios_controller.rb
class CadastroUsuariosController < ApplicationController
   def index
   @users = User.all
   authorize @users
   end  
end

app/controllers/contato_controller.rb
class ContatoController < ApplicationController
    def index
    end
end

app/controllers/pagina_inicial_controller.rb
class PaginaInicialController < ApplicationController
  def index
    @cadastro_cachorros = CadastroCachorro.all
    @users = User.all
  end
end

app/controllers/visitas_agendadas_controller.rb
class VisitasAgendadasController < ApplicationController
  before_action :set_visitas_agendada, only: [:show, :edit, :update, :destroy]

  # GET /visitas_agendadas
  # GET /visitas_agendadas.json
  def index
    @visitas_agendadas = VisitasAgendada.all
  end

  # GET /visitas_agendadas/1
  # GET /visitas_agendadas/1.json
  def show
  end

  # GET /visitas_agendadas/new
  def new
    @visitas_agendada = VisitasAgendada.new
  end

  # GET /visitas_agendadas/1/edit
  def edit
  end

  # POST /visitas_agendadas
  # POST /visitas_agendadas.json
  def create
    @visitas_agendada = VisitasAgendada.new(visitas_agendada_params)

    respond_to do |format|
      if @visitas_agendada.save
        format.html { redirect_to visitas_agendadas_path }
        format.json { render :show, status: :created, location: @visitas_agendada }
      else
        format.html { render :new }
        format.json { render json: @visitas_agendada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitas_agendadas/1
  # PATCH/PUT /visitas_agendadas/1.json
  def update
    respond_to do |format|
      if @visitas_agendada.update(visitas_agendada_params)
        format.html { redirect_to @visitas_agendada, notice: 'Visitas agendada was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitas_agendada }
      else
        format.html { render :edit }
        format.json { render json: @visitas_agendada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitas_agendadas/1
  # DELETE /visitas_agendadas/1.json
  def destroy
    @visitas_agendada.destroy
    respond_to do |format|
      format.html { redirect_to visitas_agendadas_url, notice: 'Visitas agendada was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitas_agendada
      @visitas_agendada = VisitasAgendada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitas_agendada_params
      params.require(:visitas_agendada).permit(:data, :hora, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cadastro_cachorros_helper.rb
module CadastroCachorrosHelper
end

app/helpers/cadastro_usuarios_helper.rb
module CadastroUsuariosHelper
end

app/helpers/contato_helper.rb
module ContatoHelper
end

app/helpers/criar_conta_helper.rb
module CriarContaHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/pagina_inicial_helper.rb
module PaginaInicialHelper
end

app/helpers/visitas_agendadas_helper.rb
module VisitasAgendadasHelper
end

app/views/cadastro_cachorros/edit.html.erb
<%= render 'form', cadastro_cachorro: @cadastro_cachorro %>

app/views/cadastro_cachorros/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
  <title>Lar de Adoção</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="laradocao.css">
  <link rel="stylesheet" href="modal.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="shortcut icon" href="icon.ico" type="image/x-icon"/>
</head>
<body>
  <div class="row">
    <div class="container text-center">
      <h1>ADO<span id="dest">CÃO</span></h1>      
      <p>Adote um amiguinho!</p>
    </div>
  </div>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <a class="navbar-brand">ADOCÃO</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li><%= link_to('Home', controller: 'pagina_inicial') %></li>
          <li><%= link_to('Contate-nos', controller: 'contato') %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? && current_user.isAdmin? %>
            <li><a>Olá, administrador!</a></li>
            <li><%= link_to('Usuários', cadastro_usuarios_index_path) %></li>
            <li class="active"><a>Cãezinhos</a></li>
            <li><%= link_to('Visitas', visitas_agendadas_path) %></li>
            <li><%= link_to('Editar Perfil', edit_user_registration_path) %></li>
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li> 
          <% elsif user_signed_in? && !current_user.isAdmin? %> 
            <li><a>Olá, Usuário!</a></li>
            <li><%= link_to('Editar Perfil', edit_user_registration_path) %></li>
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li> 
          <% else %>     
            <li><a>Bem Vindo(a), Visitante!</a></li>
            <li><%= link_to('Login', new_user_session_path) %></li> 
            <li><%= link_to('Cadastrar', new_user_registration_path) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="panel panel-default" style="margin:10%; margin-top:5%; margin-bottom: 0.5%">
    <div class="panel-heading text-center">Cachorros Cadastrados</div>
      <div class="panel-body" style="margin:0%">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Raça</th>
              <th>Sexo</th>
              <th>Idade</th>
            </tr>
          </thead>
          <tbody style="vertical-center">
            <% @cadastro_cachorros.each do |cadastro_cachorro| %>
              <tr>
                <td class="col-sm-3" style="vertical-align: middle; font-family: Arial"><%= cadastro_cachorro.nome %></td>
                <td class="col-sm-3" style="vertical-align: middle; font-family: Arial;"><%= cadastro_cachorro.raca %></td>
                <td class="col-sm-3" style="vertical-align: middle; font-family: Arial;"><%= cadastro_cachorro.sexo %></td>
                <td class="col-sm-2" style="vertical-align: middle; font-family: Arial;"><%= cadastro_cachorro.idade %> Anos</td>
                <td><button type="button" class="btn btn-primary"><%= link_to 'Editar', edit_cadastro_cachorro_path(cadastro_cachorro), class:"deco-none", style:"font-family:Arial" %></button></td>
                <td><button type="button" class="btn btn-danger"><%= link_to 'Deletar', cadastro_cachorro, method: :delete, data: { confirm: 'Are you sure?' }, class:"deco-none", style:"font-family:Arial" %></button></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div> 
    </div>
    <div style="margin:10%; margin-top:0.5%;"><button type="button" class="btn btn-success col-sm-12"><%= link_to 'Cadastrar novo cão', new_cadastro_cachorro_path,  class:"deco-none", style:"font-family:Arial" %></button></div>
  </div> 
</body>
</html>

app/views/cadastro_cachorros/new.html.erb
<%= render 'form', cadastro_cachorro: @cadastro_cachorro %>

app/views/cadastro_cachorros/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
 <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
 <title>Cadastre-se</title>
 <meta charset="utf-8">
 <link rel="stylesheet" href="laradocao.css">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <div class="row">
    <div class="container text-center">
      <h1>ADO<span id="dest">CÃO</span></h1>      
      <p>Adote um amiguinho!</p>
    </div>
  </div>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <a class="navbar-brand" href="#">ADOCÃO</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
            <li><%= link_to('Home', controller: 'pagina_inicial') %></li>
            <li><%= link_to('Contato', controller: 'contato') %></li>
            <li><%= link_to('Visitas agendadas', visitas_agendadas_path) %></li>
            <li><%= link_to('Cadastramento de Cãezinhos', cadastro_cachorros_path)%></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a>Olá, moderador(a)</a></li>
          <li><%= link_to('Usuários Cadastrados', cadastro_usuarios_index_path) %></li>
          <li><%= link_to('Editar Perfil', edit_user_registration_path) %></li>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container ">
    
    <p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cadastro_cachorro.nome %>
</p>

<p>
  <strong>Raca:</strong>
  <%= @cadastro_cachorro.raca %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @cadastro_cachorro.sexo %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @cadastro_cachorro.idade %>
</p>

<%= link_to 'Edit', edit_cadastro_cachorro_path(@cadastro_cachorro) %> |
<%= link_to 'Back', cadastro_cachorros_path %>
    
    </div>
  </form>
</div>
</body>
</html>

app/views/contato/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
  <title>Lar de Adoção</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="laradocao.css">
  <link rel="stylesheet" href="modal.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="shortcut icon" href="icon.ico" type="image/x-icon"/>
</head>
<body>
  <div class="row">
    <div class="container text-center">
      <h1>ADO<span id="dest">CÃO</span></h1>      
      <p>Adote um amiguinho!</p>
    </div>
  </div>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <a class="navbar-brand">ADOCÃO</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li><%= link_to('Home', controller: 'pagina_inicial') %></li>
          <li class="active"><a>Contate-nos</a></li>
          <% if user_signed_in? && !current_user.isAdmin?%> 
            <li><%= link_to('Minhas Visitas', visitas_agendadas_path) %></li>
          <% end %>  
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? && current_user.isAdmin? %>
            <li><a>Olá, administrador!</a></li>
            <li><%= link_to('Usuários', cadastro_usuarios_index_path) %></li>
            <li><%= link_to('Cãezinhos', cadastro_cachorros_path) %></li>
            <li><%= link_to('Visitas', visitas_agendadas_path) %></li>
            <li><%= link_to('Editar Perfil', edit_user_registration_path) %></li>             
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li> 
          <% elsif user_signed_in? && !current_user.isAdmin? %> 
            <li><a>Olá, Usuário!</a></li>
            <li><%= link_to('Editar Perfil', edit_user_registration_path) %></li>
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li> 
          <% else %>     
            <li><a>Bem Vindo(a), Visitante!</a></li>
            <li><%= link_to('Login', new_user_session_path) %></li> 
            <li><%= link_to('Cadastrar', new_user_registration_path) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <h2>Contate-nos</h2>
    <div class="panel panel-default">
      <div class="panel-body">
       <p>Ajude-nos a melhorar nossos serviços. Se você tem alguma sugestão fale conosco.</p>
       <p><b>E-mail:</b> lar_adocao@gmail.com</p>
       <p><b>Telefone fixo: </b>(69) 6969-6969</p>
       <p><b>Telefone celular:</b>(69) 96969-6969</p>
     </div>
   </div>
 </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ep3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/visitas_agendadas/edit.html.erb
<%= render 'form', visitas_agendada: @visitas_agendada %>

app/views/visitas_agendadas/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
  <title>Lar de Adoção</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="laradocao.css">
  <link rel="stylesheet" href="modal.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="shortcut icon" href="icon.ico" type="image/x-icon"/>
</head>
<body>
  <div class="row">
    <div class="container text-center">
      <h1>ADO<span id="dest">CÃO</span></h1>      
      <p>Adote um amiguinho!</p>
    </div>
  </div>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <a class="navbar-brand">ADOCÃO</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li><%= link_to('Home', controller: 'pagina_inicial') %></li>
          <li><%= link_to('Contate-nos', controller: 'contato') %></li>
          <% if user_signed_in? && !current_user.isAdmin?%> 
            <li class="active"><a>Minhas Visitas</a></li>
          <% end %>  
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <%if user_signed_in? && current_user.isAdmin?%>
            <li><a>Olá, administrador!</a></li>
            <li><%= link_to('Usuários', cadastro_usuarios_index_path) %></li>
            <li><%= link_to('Cãezinhos', cadastro_cachorros_path) %></li>
            <li class="active"><a>Visitas</a></li>
            <li><%= link_to('Editar Perfil', edit_user_registration_path) %></li>
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li> 
          <% else %> 
            <li><a>Olá, Usuário!</a></li>
            <li><%= link_to('Editar Perfil', edit_user_registration_path) %></li> 
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li> 
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

<div class="panel panel-default" style="margin:10%; margin-top:5%; margin-bottom: 0.5%">
  <div class="panel-heading text-center">
      <% if(current_user.isAdmin?) %>
        Visitas Agendadas
      <% else %>
        Minhas Visitas Agendadas
      <% end %>  
  </div>
    <div class="panel-body" style="margin:0%">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Data</th>
            <th>Hora</th>
            <% if(current_user.isAdmin?) %>
              <th>Id</th>
            <% end %>
          </tr>
        </thead>
        <tbody style="vertical-center">
          <% @visitas_agendadas.each do |visitas_agendada| %>
            <tr>
              <% if(current_user.isAdmin?) %>
                <td class="col-sm-4" style="vertical-align: middle; font-family: Arial"><%= visitas_agendada.data %></td>
                <td class="col-sm-4" style="vertical-align: middle; font-family: Arial;"><%= visitas_agendada.hora %></td>
                <td class="col-sm-4" style="vertical-align: middle; font-family: Arial;"><%= visitas_agendada.user_id %></td>
                <td><button type="button" class="btn btn-primary"><%= link_to 'Editar', edit_visitas_agendada_path(visitas_agendada), class:"deco-none", style:"font-family:Arial" %></button></td>
                <td><button type="button" class="btn btn-danger"><%= link_to 'Deletar', visitas_agendada, method: :delete, data: { confirm: 'Are you sure?' }, class:"deco-none", style:"font-family:Arial" %></button></td>
              <% else %>
                <% if(current_user.id == visitas_agendada.user_id) %>
                  <td class="col-sm-6" style="vertical-align: middle; font-family: Arial"><%= visitas_agendada.data %></td>
                  <td class="col-sm-6" style="vertical-align: middle; font-family: Arial;"><%= visitas_agendada.hora %></td>
                  <td><button type="button" class="btn btn-primary"><%= link_to 'Editar', edit_visitas_agendada_path(visitas_agendada), class:"deco-none", style:"font-family:Arial" %></button></td>
                  <td><button type="button" class="btn btn-danger"><%= link_to 'Deletar', visitas_agendada, method: :delete, data: { confirm: 'Are you sure?' }, class:"deco-none", style:"font-family:Arial" %></button></td> 
                <% end %>  
              <% end %>  
            </tr>
          <% end %>
        </tbody>
      </table>
    </div> 
  </div>
  <div style="margin:10%; margin-top:0.5%;"><button type="button" class="btn btn-success col-sm-12"><%= link_to 'Agendar novo horario', new_visitas_agendada_path,  class:"deco-none", style:"font-family:Arial" %></button></div>
</body>
</html>

app/views/visitas_agendadas/new.html.erb
<%= render 'form', visitas_agendada: @visitas_agendada %>

app/views/visitas_agendadas/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <title>Visitas agendadas</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="laradocao.css">
    <link rel="stylesheet" href="modal.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="shortcut icon" href="icon.ico" type="image/x-icon"/>
  </head>
  <body>
    <div class="row">
      <div class="container text-center">
        <h1>ADO<span id="dest">CÃO</span></h1>      
        <p>Adote um amiguinho!</p>
      </div>
    </div>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>                        
          </button>
          <a class="navbar-brand" href="#">ADOCÃO</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li><%= link_to('Home', controller: 'pagina_inicial') %></li>
          <li><%= link_to('Contate-nos', contato_index_path) %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <%if user_signed_in? && current_user.isAdmin?%>
            <li><a>Olá, administrador!</a></li>
            <li><%= link_to('Usuários', cadastro_usuarios_index_path) %></li>
            <li><%= link_to('Cãezinhos', cadastro_cachorros_path) %></li>
            <li><%= link_to('Visitas', visitas_agendadas_path) %></li>
            <li><%= link_to('Editar Perfil', edit_user_registration_path) %></li>
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li> 
          <% else%> 
            <li><a>Olá, Usuário!</a></li>
            <li><%= link_to('Editar Perfil', edit_user_registration_path) %></li>
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li> 
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
      <div class="container ">

        <p>
          <strong>Data:</strong>
          <%= @visitas_agendada.data %>
        </p>

        <p>
          <strong>Hora:</strong>
          <%= @visitas_agendada.hora %>
        </p>

      </form>
    </div>
    </div>
  </body>
</html>